accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('activate/<uid64>/<token>/', views.activate, name='activate'),
    path('reset_password/<uid64>/<token>/', views.reset_password, name='reset_password'),
    path('new_password/', views.new_password, name='new_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    
    path('user_profile/', views.user_profile_page, name="user_profile"),
    path('edit_user/', views.edit_user_page, name="edit_user"),
    path('user/<str:user_id>', views.user_page, name="user"),
    path('user/<str:user_id>/<str:category_slug>/', views.user_page, name="recipe_category_user"),
]

cookbook/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'cookbook'

urlpatterns = [
    path('recipes/', views.recipes_page, name='recipes'),
    path('recipes/<slug:category_slug>/', views.recipes_page, name='recipe_category'),
    path('edit_recipe/<str:idR>', views.edit_recipe_page, name="edit_recipe"),
    path('recipe/<str:idR>', views.recipe_page, name="recipe"),
    path('delete_recipe/<str:idR>', views.delete_recipe, name="delete_recipe"),
    path('create_recipe/', views.create_recipe_page, name="create_recipe"),
    path('submit_rating/<str:idR>', views.submit_rating, name='submit_rating')

]

soyummy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('cookbook/', include('cookbook.urls'))
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    User._meta.get_field('email')._unique = True
    user_img = models.ImageField(null=True, blank=True)
    description = models.TextField(max_length=400, null=True)

    @property
    def get_photo_url(self):
        if self.user_img and hasattr(self.user_img, 'url'):
            return self.user_img.url
        else:
            return "/static/images/anonym=user.png"


    def __str__(self):
        return self.user.username

accounts/forms.py
from accounts.models import UserProfile
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class RegistrationForm(UserCreationForm):
    class Meta: 
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *argv, **kwargs):
        super(RegistrationForm, self).__init__(*argv, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Enter username...'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter email..'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter password...'
        self.fields['password2'].widget.attrs['placeholder'] = 'Re-enter password...'

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'card__input'



class CookForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['user_img','description']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator

from .forms import RegistrationForm, CookForm, UserForm
from .models import UserProfile
from category.models import Category
from cookbook.filters import RecipeFilter


def send_email(request, email, user, html, subject):
    current_site = get_current_site(request)
    message = render_to_string(f'accounts/{html}.html', {
        'current_site': current_site,
        'user': user,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': default_token_generator.make_token(user),
    })
    receiver = email
    mail = EmailMessage(subject, message, to=[receiver])
    mail.send()


def register_page(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            email = form.cleaned_data['email']

            UserProfile.objects.create(
                user=user,
            )
            send_email(request, email, user, 'verification_email', 'SoYummy! Verification link')
            return redirect('/?command=verification')
    else:
        form = RegistrationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/register.html', context)


def activate(request, uid64, token):
    try:
        uid = urlsafe_base64_decode(uid64).decode()
        user = User._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError):
        user = None

    if user and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Activation was successful! Now you can start using my application!')
        return redirect('accounts:login')
    else:
        messages.error(request, 'The link is invalid! Sorry ...')
        return redirect('accounts:register')


def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            return redirect('cookbook:recipes')
        else:
            messages.info(request, 'Username or password is incorrect')

    return render(request, 'accounts/login.html')


@login_required
def logout_page(request):
    logout(request)
    return redirect('home')


@login_required
def user_profile_page(request):
    cook = request.user.userprofile
    recipes = cook.creator.all()

    context = {
        'cook': cook,
        'recipes': recipes,
    }

    return render(request, 'accounts/user_profile.html', context)


@login_required
def edit_user_page(request):
    cook = request.user.userprofile
    user = request.user
    cook_form = CookForm(instance=cook)
    user_form = UserForm(instance=user)

    if request.method == 'POST':
        cook_form = CookForm(request.POST, request.FILES, instance=cook)
        user_form = UserForm(request.POST, instance=user)
        if cook_form.is_valid() and user_form.is_valid():
            cook_form.save()
            user_form.save()
            return redirect('accounts:user_profile')

    context = {
        'cook': cook,
        'cook_form': cook_form,
        'user_form': user_form
    }

    return render(request, 'accounts/edit_user.html', context)


@login_required
def user_page(request, user_id=None, category_slug=None):
    if user_id:
        cook = get_object_or_404(UserProfile, id=user_id)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            recipes = cook.creator.filter(category=category).order_by('-creation_date')
        else:
            recipes = cook.creator.order_by('-creation_date')
        myFilter = RecipeFilter(request.GET, queryset=recipes)
        recipes = myFilter.qs
    else:
        return redirect('cookbook:recipes')

    context = {
        'cook': cook,
        'recipes': recipes,
        'myFilter': myFilter,
    }

    return render(request, 'accounts/user.html', context)


def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        if User.objects.filter(email=email):
            user = User.objects.get(email__exact=email)  # Important to get User instance, not QuerySet instance
            send_email(request, email, user, 'password_email', 'New password')
            return redirect('/?command=reset_password')
        else:
            messages.error(request, 'Account does not exist!')
            return redirect('accounts:forgot_password')

    return render(request, 'accounts/forgot_password.html')


def reset_password(request, uid64, token):
    try:
        uidb = urlsafe_base64_decode(uid64).decode()
        user = User._default_manager.get(pk=uidb)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user and default_token_generator.check_token(user, token):
        request.session['uid'] = uidb
        return redirect('accounts:new_password')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('accounts:login')


def new_password(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = User.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Password do not match!')
            return redirect('accounts:new_password')
    else:
        return render(request, 'accounts/reset_password.html')

templates/accounts/edit_user.html
{%extends 'temp_app.html'%}

{% load static %}

{% block style %} 
<link rel="stylesheet"  href="{% static 'css\navbar.css' %}">
<link rel="stylesheet"  href="{% static 'css\recipe_form.css' %}">
{% endblock style %}

{% block nav %} 
<div style="flex-grow: 1">
</div>
{% endblock nav %}

{% block content %}
{% include 'navbar.html'%}
<div class="container">
  <div class="row">
    <div class="col-3 d-none d-lg-block">
      <div class="card" style="margin: 10px">
        <img class="user_pic" src="{{cook.get_photo_url}}" alt="">
        <div class="card-body">
          <span><b>Name:</b><p>{{request.user.username}}</p></span>
          <span><b>E-mail:</b><p>{{request.user.email}}</p></span>
          <span><b>Description:</b><p>{{cook.description}}</p></span>
          <hr>
          <a href="{% url 'cookbook:create_recipe' %}">Add new recipe</a>
        </div>
      </div>
    </div>
    <div class="col-1"></div>
    <div class="col-8">
      <h5>Edit your data: </h5>
       <form action="" method="POST" enctype="multipart/form-data">
         {% csrf_token %}
         <label>Name: </label>
         <p>{{user_form.username}}</p>
         <label>Email: </label>
         <p>{{user_form.email}}</p>
         <label>Description: </label>
         <p>{{cook_form.description}}</p>
         <label>Profile image: </label>
         <p>{{cook_form.user_img}}</p>
         <input type="submit" name="Submit">
       </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/accounts/forget_password.html
{%extends 'temp_start.html'%}

{% load static %}

{% block style %} 
  <link rel="stylesheet" href="{% static 'css\sign_temp.css' %}">
  <link rel="stylesheet" href="{% static 'css\login.css' %}">
{% endblock style %}

{% block content %}
<div class="card">
  <form class="card__form" method="POST" action="">
    <img class="card__logo" src="{% static 'images\chef-logo.svg' %}" alt="">
      {% csrf_token %}
      <label for="">Forger password? Enter email: </label>
      <input type="text" name="emial" placeholder="Emial..." class="card__input form-control">
        {% for message in messages %}
        <p class="card__messages">{{message}}</p>
        {% endfor %}
      <input class="card__button button" type="submit" value="Send email">
      <div class="card__link">
        Do you have a password? <a href="{% url 'accounts:login' %}">Log in</a>
      </div>
  </form>
</div>
{% endblock %}

templates/accounts/forgot_password.html
{%extends 'temp_start.html'%}

{% load static %}

{% block style %} 
  <link rel="stylesheet" href="{% static 'css\sign_temp.css' %}">
  <link rel="stylesheet" href="{% static 'css\login.css' %}">
{% endblock style %}

{% block content %}
<div class="card">
  <form class="card__form" method="POST" action="">
    <img class="card__logo" src="{% static 'images\chef-logo.svg' %}" alt="">
      {% csrf_token %}
      <label>Forgot password? Enter email: </label>
      <input type="text" name="email" placeholder="Email..." class="card__input form-control">
        {% for message in messages %}
        <p class="card__messages">{{message}}</p>
        {% endfor %}
      <input class="card__button button" type="submit" value="Send email">
      <div class="card__link">
        Do you have a password? <a href="{% url 'accounts:login' %}">Log in</a>
      </div>
  </form>
</div>
{% endblock %}

templates/accounts/login.html
{%extends 'temp_start.html'%}

{% load static %}

{% block style %} 
  <link rel="stylesheet" href="{% static 'css\sign_temp.css' %}">
  <link rel="stylesheet" href="{% static 'css\login.css' %}">
{% endblock style %}

{% block content %}
  <div class="card">
    <form class="card__form" method="POST" action="">
      <img class="card__logo" src="{% static 'images\chef-logo.svg' %}" alt="">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username..." class="card__input form-control">
        <input type="password" name="password" placeholder="Password..." class="card__input form-control">
        {% for message in messages %}
          <p class="card__messages">{{message}}</p>
        {% endfor %}
        <input class="card__button button" type="submit" value="Login">
        <div class="card__link">
          <a href="{% url 'accounts:forgot_password' %}">Forgot password?</a>
        </div>
        <div class="card__link">
          Don't have an account? <a href="{% url 'accounts:register' %}">Sign Up</a>
        </div>
    </form>
  </div>
{% endblock %}

templates/accounts/password_email.html
{% autoescape off %}

Hi {{user.username}},

As requested, please click below link to reset your password.
http://{{current_site}}{% url 'accounts:reset_password' uid64=uid token=token %}


If you think it's not you, please ignore this email.

{% endautoescape %}

templates/accounts/register.html
{%extends 'temp_start.html'%}

{% load static %}

{% block style %} 
  <link rel="stylesheet" href="{% static 'css\sign_temp.css' %}">
{% endblock style %}

{% block content %}
  <div class="card">
    <form class="card__form" method="POST" action="">
      <img class="card__logo" src="{% static 'images\chef-logo.svg' %}" alt="">
        {% csrf_token %}
        {{form.username}}
        {{form.email}}
        {{form.password1}}
        {{form.password2}}

        {% if form.errors %}
          {% for field in form %}
              {% for error in field.errors %}
                  <div class="card__messages">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}
          {% endfor %}
        {% endif %}
      <input class="card__button button" type="submit" name="Create User" value="Register">
      <div class="card__link">
        Already have an account? <a href="{% url 'accounts:login' %}" class="ml-2">Log in</a>
      </div>
    </form>
  </div>
 
 
{% endblock %}

templates/accounts/reset_password.html
{%extends 'temp_start.html'%}

{% load static %}

{% block style %} 
  <link rel="stylesheet" href="{% static 'css\sign_temp.css' %}">
  <link rel="stylesheet" href="{% static 'css\login.css' %}">
{% endblock style %}

{% block content %}
  <div class="card">
    <form class="card__form" method="POST" action="">
      <img class="card__logo" src="{% static 'images\chef-logo.svg' %}" alt="">
        {% csrf_token %}
        <label>Enter new password: </label>
        <input type="password" name="password" placeholder="Password..." class="card__input form-control">
        <input type="password" name="confirm_password" placeholder="Confirm password..." class="card__input form-control">
          {% for message in messages %}
          <p class="card__messages">{{message}}</p>
          {% endfor %}
        <input class="card__button button" type="submit" value="Change">
    </form>
  </div>
{% endblock %}

templates/accounts/user.html
{%extends 'temp_app.html'%}

{% load static %}
{% load widget_tweaks %}

{% block style %} 
<link rel="stylesheet" href="{% static 'css\user.css' %}">
<link rel="stylesheet"  href="{% static 'css\navbar.css' %}">
<link rel="stylesheet" href="{% static 'css\searcher.css' %}">
{% endblock style %}

{% block nav %} 
<div class="searcher">
  <form method="GET">
    {{myFilter.form.search}}
    <button class="searcher__button" type="submit">Search</button>
  </form>
</div>
{% endblock nav %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-ligth">
  <a class="navbar-brand d-lg-none" href="{% url 'cookbook:recipes' %}">
    <img class="nav-logo" src="{% static 'images\chef_black.svg' %}" alt=""></a>
  <a class="navbar-brand d-none d-lg-block" href="{% url 'accounts:user' cook.id %}">Categories</a>
  <button class="navbar-toggler" type="button"
          data-toggle="collapse"
          data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item ">
        <a class="nav-link 	d-lg-none dropdown-item" href="{% url 'accounts:user_profile' %}">Your profile</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link 	d-lg-none dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
      <li class="nav-item d-lg-none ">
        <a class="nav-link dropdown-item" href="{% url 'accounts:user' cook.id %}">All</a>
      </li>
      {% for category in categories %}
      <li class="nav-item ">
        <a class="nav-link " href="{% url 'accounts:recipe_category_user' cook.id category.slug %}">{{category.name}}</a>
      </li>
      {% endfor %}
    </ul>
    <form class="form-inline my-2 my-lg-0 d-lg-none">
        {% render_field myFilter.form.search class="form-control mr-sm-2" %}
      <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="card user">
        <img class="user__pic" src="{{cook.get_photo_url}}" alt="">
        <div class="card-body">
          <span><b>Name:</b><p>{{cook.user.username}}</p></span>
          <span><b>E-mail:</b><p>{{cook.user.email}}</p></span>
          <span><b>Description:</b> <p>{{cook.description}}</p></span>
        </div>
      </div>
    </div>
    <div class="col-md"></div>
      <div class="col-md-8 recipes">
            <h5 class="recipe-title">Recipes: </h5>
            {%for recipe in recipes %}
              <div class="card recipe" style="width: 18rem;">
                <a href="{% url 'cookbook:recipe' recipe.id %}">
                  <img src="{{recipe.get_photo_url}}" class="card-img-top" alt="..."></a>
                <div class="card-body">
                  <h5 class="card-title">{{recipe.name}}</h5>
                  <a href="{% url 'cookbook:recipe' recipe.id %}">See recipe</a>
                </div>
            </div>
          {%endfor%}
      </div>
  </div>
</div>
{% endblock content %}


{% block script %}
<script>
  search = document.querySelector('#id_search')
  search.setAttribute('placeholder', 'Enter the phrase ...')
</script>
{% endblock script %}

templates/accounts/user_profile.html
{%extends 'temp_app.html'%}

{% load static %}

{% block style %} 
<link rel="stylesheet"  href="{% static 'css\user_profile.css' %}">
<link rel="stylesheet"  href="{% static 'css\navbar.css' %}">
{% endblock style %}

{% block nav %} 
<div style="flex-grow: 1">
</div>
{% endblock nav %}

{% block content %}
{% include 'navbar.html'%}
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="card user">
        <img class="user__pic" src="{{cook.get_photo_url}}" alt="">
        <div class="card-body">
          <span><b>Name:</b><p>{{request.user.username}}</p></span>
          <span><b>E-mail:</b><p>{{request.user.email}}</p></span>
          <span><b>Description:</b> <p>{{cook.description}}</p></span>
          <hr>
          <a href="{% url 'accounts:edit_user' %}">Settings</a>
          <hr>
          <a href="{% url 'cookbook:create_recipe' %}">Add new recipe</a>
        </div>
      </div>
    </div>
    <div class="col-md"></div>
      <div class="col-md-8 recipes">
            <h5 class="recipes__title">Your recipes: </h5>
            {% if recipes %}
              {%for recipe in recipes %}
                <div class="card recipe-card" style="width: 18rem;">
                  <img src="{{recipe.get_photo_url}}" class="card-img-top" alt="...">
                  <div class="card-body recipe-card__panel">
                    <h5 class="recipe-card__title">{{recipe.name}}</h5>
                    <hr>
                    <a class="recipe-card__link" href="{% url 'cookbook:delete_recipe' recipe.id %}">Delete</a>
                    <a class="recipe-card__link" href="{% url 'cookbook:edit_recipe' recipe.id %}">Edit</a>
                    <a class="recipe-card__link" href="{% url 'cookbook:recipe' recipe.id %}">See</a>
                  </div>
              </div>
            {%endfor%}
            {% else %}
            <h6>You don't have any recipes, add something!</h6>
          {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

templates/accounts/verification_email.html
{% autoescape off %}

Hi {{user.username}},

We just need to verify your email address before you can access SoYummy.

Verify your email address http://{{current_site}}{% url 'accounts:activate' uid64=uid token=token %}

Thanks! – The SoYummy team

{% endautoescape %}