accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('activate/<uid64>/<token>/', views.activate, name='activate'),
    path('reset_password/<uid64>/<token>/', views.reset_password, name='reset_password'),
    path('new_password/', views.new_password, name='new_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    
    path('user_profile/', views.user_profile_page, name="user_profile"),
    path('edit_user/', views.edit_user_page, name="edit_user"),
    path('user/<str:user_id>', views.user_page, name="user"),
    path('user/<str:user_id>/<str:category_slug>/', views.user_page, name="recipe_category_user"),
]

cookbook/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'cookbook'

urlpatterns = [
    path('recipes/', views.recipes_page, name='recipes'),
    path('recipes/<slug:category_slug>/', views.recipes_page, name='recipe_category'),
    path('edit_recipe/<str:idR>', views.edit_recipe_page, name="edit_recipe"),
    path('recipe/<str:idR>', views.recipe_page, name="recipe"),
    path('delete_recipe/<str:idR>', views.delete_recipe, name="delete_recipe"),
    path('create_recipe/', views.create_recipe_page, name="create_recipe"),
    path('submit_rating/<str:idR>', views.submit_rating, name='submit_rating')

]

soyummy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('cookbook/', include('cookbook.urls'))
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/footer.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/footer.css' %}">
</head>
<body>
  <footer>
    <hr>
    <div class="content">
      <h6>©Copyright by AM</h6>
    </div>
  </footer>
</body>

templates/home.html
{%extends 'temp_start.html'%}

{% load static %}

{% block style %} 
  <link rel="stylesheet" href="{% static 'css\start.css' %}">
{% endblock style %}

{% block content %}
   <div class="cointainer">
     <div class="title">
      {% if request.GET.command == 'verification' %}
      <h1>Thank you for registering with us. We have sent you a verification email to your email address. Enter link and active your account!</h1>
      {% else %}
      {% if request.GET.command == 'reset_password' %}
      <h1>Password reset email has been sent to your email address.</h1>
      {% else %}
       <h1>Do you like cooking? Do you have a lot of great ideas and want to get to know other people's ideas?
       </h1>
       {% endif %}
       {% endif %}
       <a type="button" href="{% url 'accounts:register' %}" class="button">Join us</a>
       <a type="button" href="{% url 'accounts:login' %}" class="button">Log in</a>

     </div>
   </div>
{% endblock %}

templates/navbar.html
{% load static %}

<nav class="navbar d-lg-none navbar-expand-lg navbar-light bg-ligth">
  <a class="navbar-brand d-lg-none" href="{% url 'cookbook:recipes' %}"><img class="nav-logo" src="{% static 'images\chef_black.svg' %}" alt=""></a>
  <a class="navbar-brand d-none d-lg-block" href="{% url 'cookbook:recipes' %}">Categories</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link dropdown-item" href="{% url 'accounts:user_profile' %}">Your profile</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
    </ul>
  </div>
</nav>

templates/temp_app.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="{%  static 'icon\favicon.ico' %}" />
  <title>SoYummy!</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css\app.css' %}">
  {% block style %} 
  {% endblock style %}
</head>
<body>
  <div class="d-none d-lg-block">
  <div class="header">
    <a class="header__logo-link" href="{% url 'cookbook:recipes' %}"><img class="header__logo" src="{% static 'images\chef.svg' %}" alt=""></a>
    {% block nav %}
    {% endblock %}
    <div class="header__profile">
      <a class="header__user" href="{%  url 'accounts:user_profile'%}"><p class="header__greeting">Hello {{request.user.username}}!</p><img class="header__user-icon" src="{% static 'images/profile-user.svg' %}"  alt=""></a>
      <a class="header__logout" href="{% url 'accounts:logout' %}">Logout  <img class="header__logout-icon" src="{% static 'images/logout.svg' %}"  alt=""></a>

    </div>
  </div>
</div>
<main class="main-panel">
  {% block content %}
  {% endblock %}
</main>
  {% include 'footer.html'%}
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  
  {% block script %}
  {% endblock %}
</body>
</html>

templates/temp_start.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="{%  static 'icon\favicon.ico' %}" />
  <title>SoYummy!</title>
  <link rel="stylesheet" href="{% static 'css\temp_start.css' %}">
  {% block style %} 
  {% endblock style %}
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}

</body>
</html>