accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('activate/<uid64>/<token>/', views.activate, name='activate'),
    path('reset_password/<uid64>/<token>/', views.reset_password, name='reset_password'),
    path('new_password/', views.new_password, name='new_password'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    
    path('user_profile/', views.user_profile_page, name="user_profile"),
    path('edit_user/', views.edit_user_page, name="edit_user"),
    path('user/<str:user_id>', views.user_page, name="user"),
    path('user/<str:user_id>/<str:category_slug>/', views.user_page, name="recipe_category_user"),
]

cookbook/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'cookbook'

urlpatterns = [
    path('recipes/', views.recipes_page, name='recipes'),
    path('recipes/<slug:category_slug>/', views.recipes_page, name='recipe_category'),
    path('edit_recipe/<str:idR>', views.edit_recipe_page, name="edit_recipe"),
    path('recipe/<str:idR>', views.recipe_page, name="recipe"),
    path('delete_recipe/<str:idR>', views.delete_recipe, name="delete_recipe"),
    path('create_recipe/', views.create_recipe_page, name="create_recipe"),
    path('submit_rating/<str:idR>', views.submit_rating, name='submit_rating')

]

soyummy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('cookbook/', include('cookbook.urls'))
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cookbook/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey
from django.db.models import Avg, Count

from category.models import Category
from accounts.models import UserProfile


class Recipe(models.Model):
    LEVEL = (
        ('Easy', 'Easy'),
        ('Medium', 'Medium'),
        ('Hard', 'Hard'),
    )
    cook = models.ForeignKey(UserProfile, null=True, blank=True, related_name='creator', on_delete=models.SET_NULL)
    name = models.CharField(max_length=200)
    recipe_img = models.ImageField(null=True, blank=True)
    category = models.ManyToManyField(Category)
    description = models.TextField(max_length=1000, null=True)
    preparation_time = models.FloatField(blank=True, null=True)
    level = models.CharField(max_length=30, null=True, choices=LEVEL)
    creation_date = models.DateTimeField(auto_now_add=True)

    @property
    def get_photo_url(self):
        if self.recipe_img and hasattr(self.recipe_img, 'url'):
            return self.recipe_img.url
        else:
            return "/static/images/pesto.jpg"

    def __str__(self):
        return self.name

    def average_rating(self):
        rating = Rating.objects.filter(recipe=self).aggregate(average=Avg('rating'))
        average = 0
        if rating['average']:
            average = float("{:.2f}".format(rating['average']))
        return average

    def count_rating(self):
        rating = Rating.objects.filter(recipe=self).aggregate(count=Count('id'))
        count = 0
        if rating['count']:
            count = int(rating['count'])
        return count


class Ingredient(models.Model):
    recipe = ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    quantity = models.DecimalField(max_digits=5, decimal_places=1, blank=True, null=True)
    measurement = models.CharField(max_length=30, blank=True, null=True)


class Rating(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=CASCADE)
    rating = models.FloatField()
    creation_date = models.DateTimeField(auto_now_add=True)

cookbook/forms.py
from django.forms import ModelForm

from .models import Ingredient, Recipe, Rating


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'
        exclude = ['cook']


class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name', 'quantity', 'measurement']


class RatingForm(ModelForm):
    class Meta:
        model = Rating
        fields = ['rating']

cookbook/views.py
from django.forms.models import modelformset_factory
from django.http.response import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import formset_factory, inlineformset_factory

from .models import Ingredient, Rating, Recipe
from .forms import RecipeForm, IngredientForm, RatingForm
from .filters import RecipeFilter
from category.models import Category


@login_required
def recipes_page(request, category_slug=None):
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        recipes = Recipe.objects.filter(category=category)
    else:
        recipes = Recipe.objects.all().order_by('-creation_date')

    myFilter = RecipeFilter(request.GET, queryset=recipes)
    recipes = myFilter.qs

    paginator = Paginator(recipes, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_number': page_number,
        'page_obj': page_obj,
        'myFilter': myFilter,
    }
    return render(request, 'cookbook/recipes.html', context)


@login_required
def edit_recipe_page(request, idR):
    cook = request.user.userprofile
    recipe = Recipe.objects.get(id=idR)
    ingredients = Ingredient.objects.filter(recipe=recipe)
    IngredientFormSet = modelformset_factory(Ingredient, form=IngredientForm)
    formset = IngredientFormSet(queryset=ingredients)
    form = RecipeForm(instance=recipe)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        formset = IngredientFormSet(request.POST or None, queryset=ingredients)
        if form.is_valid():
            form.save()
            if formset.is_valid():
                Ingredient.objects.filter(recipe=recipe).delete()
                for form_ing in formset:
                    if form_ing.is_valid() and form_ing.cleaned_data.get('name'):
                        create_ingredient(form_ing, recipe)
                return redirect('accounts:user_profile')
        else:
            messages.error('Some field is required!')
            formset = IngredientFormSet(queryset=ingredients)

    context = {
        'form': form,
        'recipe': recipe,
        'cook': cook,
        'formset': formset,
    }
    return render(request, 'cookbook/edit_recipe.html', context)


@login_required
def recipe_page(request, idR):
    recipe = Recipe.objects.get(id=idR)
    ingredients = Ingredient.objects.filter(recipe=recipe)
    cook = recipe.cook
    categories = recipe.category.all()
    ingredients_to_string = []

    for ingredient in ingredients:
        ing_str = str(ingredient.quantity)
        if ingredient.quantity and ing_str.split('.')[1] == '0':
            ing_str = ing_str[:-2]
        ingredients_to_string.append(
            f'{ingredient.name} {ing_str if ingredient.quantity else ""}\
                {ingredient.measurement if ingredient.measurement else ""}')

    context = {
        'cook': cook,
        'recipe': recipe,
        'categories': categories,
        'ingredients': ingredients_to_string,
    }

    return render(request, 'cookbook/recipe.html', context)


def create_ingredient(form, recipe):
    cleaned_data = form.cleaned_data
    name = cleaned_data.get('name')
    quantity = cleaned_data.get('quantity')
    measurement = cleaned_data.get('measurement')
    ingredient = Ingredient(recipe=recipe, name=name, quantity=quantity, measurement=measurement)
    ingredient.save()


@login_required
def create_recipe_page(request):
    cook = request.user.userprofile
    recipe = Recipe(cook=cook)
    form = RecipeForm(instance=recipe)
    IngredientFormSet = formset_factory(IngredientForm, extra=2)

    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        formset = IngredientFormSet(request.POST)
        if form.is_valid() and formset.is_valid():
            form.save()
            for form in formset:
                if form.is_valid() and form.cleaned_data.get('name'):
                    create_ingredient(form, recipe)
            return redirect('accounts:user_profile')
    else:
        formset = IngredientFormSet()

    context = {
        'form': form,
        'formset': formset
    }
    return render(request, 'cookbook/create_recipes.html', context)


@login_required
def delete_recipe(request, idR):
    recipe = Recipe.objects.get(id=idR)
    recipe.delete()
    return redirect('accounts:user_profile')


def submit_rating(request, idR):
    recipe = Recipe.objects.filter(id=idR)[0]
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            rating = Rating.objects.get(user__id=request.user.userprofile.id, recipe=recipe)
            form = RatingForm(request.POST, instance=rating)
            form.save()
            return redirect(url)
        except Rating.DoesNotExist:
            form = RatingForm(request.POST)
            if form.is_valid():
                cleaned_data = form.cleaned_data
                rating = cleaned_data.get('rating')
                rating = Rating(rating=rating, user=request.user.userprofile, recipe=recipe)
                rating.save()
                return redirect(url)
            else:
                return Http404(form.errors)

templates/cookbook/create_recipes.html
{%extends 'temp_app.html'%}

{% load static %}

{% block style %} 
<link rel="stylesheet"  href="{% static 'css\navbar.css' %}">
<link rel="stylesheet"  href="{% static 'css\recipe_form.css' %}">
{% endblock style %}

{% block nav %} 
<div style="flex-grow: 1">
</div>
{% endblock nav %}

{% block content %}
{% include 'navbar.html'%}
<div class="container">
  <div class="row">
    <div class="col-3 d-none d-lg-block">
      <div class="card" style="margin: 10px">
        <img class="user_pic" src="{{request.user.userprofile.get_photo_url}}" alt="">
        <div class="card-body">
          <span><b>Name:</b><p>{{request.user.username}}</p></span>
          <span><b>E-mail:</b><p>{{request.user.email}}</p></span>
          <span><b>Description:</b><p>{{request.user.userprofile.description}}</p></span>
          <hr>
          <a href="{% url 'accounts:edit_user' %}">Settings</a>
        </div>
      </div>
    </div>
    <div class="col-1"></div>
    <div class="col-8">
            <h5>Add new recipe: </h5>
            <form id="container" action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <!-- {{form.cook}} -->
              <label>Dish name</label>
              <p>{{form.name}}</p>
              <label>Choose category (click Ctrl to select more)</label>
              <p>{{form.category}}</p>
              <label>Choose level of difficulty: </label>
              <p>{{form.level}}</p>
              <label>Preparation time in hour: </label>
              <p>{{form.preparation_time}}</p>
              <label>Ingredients: </label>
              {{ formset.management_form }}
                  {% for form in formset %}
                    <div class="ing-form">
                      <hr>
                      {{ form.as_p}}
                    </div>
                  {% endfor %}
              <button class="button" id="add-more" type="button">Add More</button>
              <br>
              <label>Describe</label>
              <p>{{form.description}}</p>
              <label>Image</label>
              <p>{{form.recipe_img}}</p>
              <input type="submit" name="Submit">
            </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block script %}
<script>
    let ingForm = document.querySelectorAll(".ing-form")
    let container = document.querySelector("#container")
    let addButton = document.querySelector("#add-more")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
    let formNum = ingForm.length-1
    addButton.addEventListener('click', addForm)
    function addForm(e){
        e.preventDefault()
        let newForm = ingForm[0].cloneNode(true)
        let formRegex = RegExp(`form-(\\d){1}-`,'g')
        formNum++
        newForm.innerHTML = newForm.innerHTML.replace(formRegex,'form-'+formNum+'-')
        container.insertBefore(newForm, addButton)
        
        totalForms.setAttribute('value', `${formNum+1}`)
    }
</script>
{% endblock %}

templates/cookbook/edit_recipe.html
{%extends 'temp_app.html'%}

{% load static %}

{% block style %} 
<link rel="stylesheet"  href="{% static 'css\navbar.css' %}">
<link rel="stylesheet"  href="{% static 'css\recipe_form.css' %}">
{% endblock style %}

{% block nav %} 
<div style="flex-grow: 1">
</div>
{% endblock nav %}

{% block content %}
{% include 'navbar.html'%}
<div class="container">
  <div class="row">
    <div class="col-3 d-none d-lg-block">
      <div class="card" style="margin: 10px">
        <img class="user_pic" src="{{request.user.userprofile.get_photo_url}}" alt="">
        <div class="card-body">
          <span><b>Name:</b><p>{{request.user.username}}</p></span>
          <span><b>E-mail:</b><p>{{request.user.email}}</p></span>
          <span><b>Description:</b><p>{{request.user.userprofile.description}}</p></span>
          <hr>
          <a href="{% url 'accounts:edit_user' %}">Settings</a>
          <hr>
          <a href="{% url 'cookbook:create_recipe' %}">Add new recipe</a>
        </div>
      </div>
    </div>
    <div class="col-1"></div>
    <div class="col-8">
                    {% if messages %}
                      {% for message in messages %}
                      <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      {% endfor %}
              {% endif %}
            <h5>Edit recipe: </h5>
            <form action="" id="container" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <label>Dish name</label>
              <p>{{form.name}}</p>
              <label>Choose category (click Ctrl to select more)</label>
              <p>{{form.category}}</p>
              <label>Choose level of difficulty: </label>
              <p>{{form.level}}</p>
              <label>Preparation time in hour: </label>
              <p>{{form.preparation_time}}</p>
              <label>Ingredients: </label>
              {{ formset.management_form }}
                  {% for form in formset %}
                    <div class="ing-form">
                      <hr>
                      {{ form.as_p}}
                    </div>
                  {% endfor %}
              <button class="button" id="add-more" type="button">Add More</button>
              <br>
              <label>Describe: </label>
              <p>{{form.description}}</p>
              <label>Image</label>
              <p>{{form.recipe_img}}</p>
              <input type="submit" name="Submit">
            </form>
    </div>
  </div>
</div>
{% endblock content %}


{% block script %}
<script>
    let ingForm = document.querySelectorAll(".ing-form")
    let container = document.querySelector("#container")
    let addButton = document.querySelector("#add-more")
    let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
    let formNum = ingForm.length-1
    addButton.addEventListener('click', addForm)
    function addForm(e){
        e.preventDefault()
        let newForm = ingForm[0].cloneNode(true)
        let formRegex = RegExp(`form-(\\d){1}-`,'g')
        formNum++
        newForm.innerHTML = newForm.innerHTML.replace(formRegex,`form-${formNum}-`)
        container.insertBefore(newForm, addButton)
        document.getElementById(`id_form-${formNum}-name`).setAttribute('value', '')
        document.getElementById(`id_form-${formNum}-quantity`).setAttribute('value', '')
        document.getElementById(`id_form-${formNum}-measurement`).setAttribute('value', '')
        
        totalForms.setAttribute('value', `${formNum+1}`)
    }
</script>
{% endblock %}

templates/cookbook/recipe.html
{%extends 'temp_app.html'%}

{% load static %}

{% block style %} 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css\recipe.css' %}">
<link rel="stylesheet" href="{% static 'css\navbar.css' %}">
<link rel="stylesheet" href="{% static 'css\rating.css' %}">
{% endblock style %}

{% block nav %} 
<div style="flex-grow: 1">
</div>
{% endblock nav %}

{% block content %}
{% include 'navbar.html'%}
<div class="container">
  <div class="row">
    <div class="col-7">
      <h6>Create by:
        {% if recipe.cook.user == request.user %}
        <a href="{% url 'accounts:user_profile' %}">{{recipe.cook.user.username}}</a>
        {% else %}
        <a href="{% url 'accounts:user' recipe.cook.id %}">{{recipe.cook.user.username}}</a>
        {% endif %}
        </h6>
      <h5>{{recipe.name}}</h5>
      <h6>Category:
      {% for category in categories %}
      {{category}},
      {% endfor %}
      </h6>
      <div class="rating-star">
        <span>
          <i class="fa fa-star{% if recipe.average_rating < 0.5 %}-o{% elif recipe.average_rating >= 0.5 and recipe.average_rating < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if recipe.average_rating < 1.5 %}-o{% elif recipe.average_rating >= 1.5 and recipe.average_rating < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if recipe.average_rating < 2.5 %}-o{% elif recipe.average_rating >= 2.5 and recipe.average_rating < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if recipe.average_rating < 3.5 %}-o{% elif recipe.average_rating >= 3.5 and recipe.average_rating < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
          <i class="fa fa-star{% if recipe.average_rating < 4.5 %}-o{% elif recipe.average_rating >= 4.5 and recipe.average_rating < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
<span>{{recipe.average_rating}}</span>
<p>{{recipe.count_rating}} people rated</p>
          </span>
      </div>
      <form action="{% url 'cookbook:submit_rating' recipe.id %}" method="POST">
        {% csrf_token %}
          <div class="rate">
            <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
            <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
            <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
            <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
            <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
            <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
            <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
            <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
            <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
            <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
            <br>
            <input type="submit" value="Submit Rating" class="button">
          </div>
        </form>
    </div>
    <div class="col-md">
      <img class="image img-thumbnail" src="{{recipe.get_photo_url}}" class="card-img-top" alt="...">
    </div>
  </div>
  <div class="row">
    <b>Ingredients: </b>
    {% for ingredient in ingredients %}
      <span>{{ingredient}}</span>
    {% endfor %}
    <b class="description">Description: </b><p>{{recipe.description}}</p>    
  </div>

</div>
{% endblock content %}

templates/cookbook/recipes.html
{%extends 'temp_app.html'%}

{% load static %}
{% load widget_tweaks %}

{% block style %} 
<link rel="stylesheet" href="{% static 'css\recipes.css' %}">
<link rel="stylesheet" href="{% static 'css\searcher.css' %}">
{% endblock style %}

{% block nav %} 
<div class="searcher">
    <form method="GET">
      {{myFilter.form.search}}
      <button class="searcher__button" type="submit">Search</button>
    </form>
</div>
{% endblock nav %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-ligth">
  <a class="navbar-brand d-lg-none" href="{% url 'cookbook:recipes' %}"><img class="nav-logo" src="{% static 'images\chef_black.svg' %}" alt=""></a>
  <a class="navbar-brand d-none d-lg-block" href="{% url 'cookbook:recipes' %}">Categories</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link 	d-lg-none dropdown-item" href="{% url 'accounts:user_profile' %}" >Your profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link 	d-lg-none dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
      {% for category in categories %}
      <li class="nav-item">
        <a class="nav-link dropdown-item" href="{{ category.get_url }}">{{category.name}}</a>
      </li>
      {% endfor %}
    </ul>
    <form class="form-inline my-2 my-lg-0 d-lg-none">
        {% render_field myFilter.form.search class="form-control mr-sm-2" %}
      <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container">
  <div class="row "> 
  {%for obj in page_obj %}
      <div class="card">
        <a  class="card__img-link" href="{% url 'cookbook:recipe' obj.id %}"><img src="{{obj.get_photo_url}}" class="card__img-top card-img-top" alt="Photo of dish">
          <h5 class="card__time"><img src="{% static 'images/clock.svg' %}" alt=""><img src="{% static 'images/bars-level.svg' %}" alt=""> 
          <p>{{obj.preparation_time}}h</p><p>{{obj.level}}</p></h5></a>
        <div class="card-body">
          <h5 class="card-title">{{obj.name}}</h5>
          <a class="card__recipe-link" href="{% url 'cookbook:recipe' obj.id %}">See recipe</a>
        </div>
    </div>
  {%endfor%}
  </div> 
{% if page_obj.paginator.num_pages > 1 %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
      <li>
        {% if page_obj.has_previous %}
          <a class="arrow-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">
            <img class="arrow" src="{% static 'images/left-arrow.svg' %}" alt=""></a>
        {% endif %}
      </li>
      <li>
        {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </li>
      <li class="page-item">
        {% if page_obj.has_next %}
          <a class="arrow-link" href="?page={{ page_obj.next_page_number }}">
            <img class="arrow" src="{% static 'images/right-arrow-angle.svg' %}" alt=""></a>
        {% endif %}
      </li>
    </ul>
  </nav>
{% endif %}
</div>


{% endblock content %}


{% block script %}
<script>
  search = document.querySelector('#id_search')
  search.setAttribute('placeholder', 'Enter the phrase ...')
</script>
{% endblock script %}